// 데이터플로 설계에서 도출된 뮤테이션 종류를 정의
export const AUTH_LOGIN: string = 'AUTH_LOGIN'
export const AUTH_LOGOUT: string = 'AUTH_LOGOUT'
export const FETCH_ALL_TASKLIST: string = 'FETCH_ALL_TASKLIST'
export const ADD_TASK: string = 'ADD_TASK'
export const UPDATE_TASK: string = 'UPDATE_TASK'
export const REMOVE_TASK: string = 'REMOVE_TASK'
export const MOVE_TASK_FROM: string = 'MOVE_TASK_FROM'
export const MOVE_TO_TASK: string = 'MOVE_TO_TASK'
export const MOVE_TASK_DONE: string = 'MOVE_TASK_DONE'
